version: 2.1

jobs:
  runner-test:
    machine: true
    resource_class: exo/hardware
    steps:
      - run:
          name: Gather System Information
          command: |
            # Create directory for artifacts
            mkdir -p /tmp/system-info
            
            # Get hostname and IP address
            echo "Hostname: $(hostname)" > /tmp/system-info/system-details.txt
            echo -e "\nIP Addresses:" >> /tmp/system-info/system-details.txt
            ifconfig | grep "inet " | awk '{print $2}' >> /tmp/system-info/system-details.txt
            
            # Get CPU information
            echo -e "\nCPU Information:" >> /tmp/system-info/system-details.txt
            sysctl -n machdep.cpu.brand_string >> /tmp/system-info/system-details.txt
            echo "CPU Cores: $(sysctl -n hw.ncpu)" >> /tmp/system-info/system-details.txt
            echo "Architecture: $(uname -m)" >> /tmp/system-info/system-details.txt
            
            # Get memory information
            echo -e "\nMemory Information:" >> /tmp/system-info/system-details.txt
            echo "Total Memory (GB): $(( $(sysctl -n hw.memsize) / 1024 / 1024 / 1024 ))" >> /tmp/system-info/system-details.txt
            
            # Add timestamp
            echo -e "\nTimestamp: $(date)" >> /tmp/system-info/system-details.txt

      - store_artifacts:
          path: /tmp/system-info
          destination: system-info

workflows:
  testing:
    jobs:
      - runner-test