version: 2.1

jobs:
  check_chip:
    parameters:
      target_chip:
        type: string
    machine: true
    resource_class: "exo/hardware"
    steps:
      - run:
          name: Check for chip
          command: |
            echo "Hostname: $(hostname)"
            CHIP=$(sysctl -n machdep.cpu.brand_string | grep -o "M[1-4]" || echo "Unknown")
            echo "Found chip: $CHIP"
            
            if [[ "$CHIP" == "<< parameters.target_chip >>" ]]; then
              echo "Match found! Hello $CHIP"
              exit 0
            else
              echo "This machine doesn't have << parameters.target_chip >>"
              exit 1
            fi

workflows:
  check-chips:
    jobs:
      - check_chip:
          matrix:
            parameters:
              target_chip: ["M3", "M4"]