version: 2.1

jobs:
  check_chip:
    machine: true
    resource_class: exo/hardware
    parameters:
      target_chip:
        type: string
        description: "The Apple chip to check for (M1 | M2 | M3 | M4)"
    steps:
      - checkout
      - run:
          name: Check Chip and Perform Actions
          command: |
            set -x  # Enable debug mode

            # Retrieve system information
            HOSTNAME=$(hostname)
            IPADDR=$(ifconfig | grep 'inet ' | grep -v 127.0.0.1 | awk '{print $2}')
            CHIP=$(sysctl -n machdep.cpu.brand_string | grep -o "M[1-4]" || echo "Unknown")
            
            # Display machine details
            echo "=== Machine Details ===="
            echo "Hostname: $HOSTNAME"
            echo "IP Address: $IPADDR"
            echo "Chip: $CHIP"
            echo "========================"

            # Check if the machine has the target chip
            if [[ "$CHIP" == "<< parameters.target_chip >>" ]]; then
              echo "✅ Runner has the << parameters.target_chip >> chip."
              
              # Perform environment setup and execute exo
              echo "🔄 Performing environment setup..."
              sh install.sh
              echo "🚀 Executing exo..."
              exo
              echo "✅ Exo executed successfully."
            else
              echo "❌ Runner does not have the << parameters.target_chip >> chip. No changes."
            fi

workflows:
  benchmark:
    jobs:
      # - check_chip:
      #     name: "Check Chip M1"
      #     target_chip: "M1"
      - check_chip:
          name: "Check Chip M2"
          target_chip: "M2"
      # - check_chip:
      #     name: "Check Chip M3"
      #     target_chip: "M3"
      # - check_chip:
      #     name: "Check Chip M4"
      #     target_chip: "M4"
