version: 2.1

workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    resource_class: exo/hardware-runner-j4r75p27fq
    steps:
      - run: echo "Hi I'm on Runners!" 