version: 2.1

parameters:
  target_chips:
    type: string
    default: "M1,M2"
    description: "Comma-separated chip types"

jobs:
  check_chip:
    parameters:
      runner_name:
        type: string
    machine: true
    resource_class: << parameters.runner_name >>
    steps:
      - run:
          name: Get and compare chip info
          command: |
            CHIP=$(sysctl -n machdep.cpu.brand_string | grep -o "M[1-4]" || echo "Unknown")
            
            if echo "<< pipeline.parameters.target_chips >>" | tr ',' '\n' | grep -q "$CHIP"; then
              echo "Found matching chip: $CHIP"
              echo "Hello $CHIP"
              exit 0
            else
              echo "Chip $CHIP not in target list"
              exit 1
            fi

workflows:
  check-chips:
    jobs:
      - check_chip:
          matrix:
            parameters:
              runner_name: ["exo/hardware", "exo/hardware"]