version: 2.1
#
workflows:
  testing:
    jobs:
      - runner

jobs:
  runner:
    machine: true
    resource_class: exo/hardware
    steps:
      - checkout
      - run:
          name: init
          command: |
            sh install.sh
      - run:
          name: ping
          command: |
            exo --prompt "hello"
      # - run:
      #     name: benchmark
      #     command: |
      #       python3 $HOME/Library/Preferences/com.circleci.runner/workdir/.circleci/bench.py
