version: 2.1

parameters:
  target_chips:
    type: string
    default: "M1,M2"
    description: "comma-separated chip types"

jobs:
  check_chip:
    parameters:
      runner_name:
        type: string
    machine:
      image: exo/hardware
      name: << parameters.runner_name >>
    steps:
      - run:
          name: Get and compare chip info
          command: |
            # Get chip info
            CHIP=$(sysctl -n machdep.cpu.brand_string | grep -o "M[1-4]" || echo "Unknown")
            
            # Check if chip matches target
            if echo "<< pipeline.parameters.target_chips >>" | tr ',' '\n' | grep -q "$CHIP"; then
              echo "Found matching chip: $CHIP"
              echo "Hello $CHIP"
              exit 0
            else
              echo "Chip $CHIP not in target list"
              exit 1
            fi

workflows:
  check-chips:
    jobs:
      - check_chip:
          name: check-e0
          runner_name: hardware-runner-e0
          matrix:
            parameters:
              runner_name: ["hardware-runner-e0", "hardware-runner-e1"]