version: 2.1

workflows:
  testing:
    jobs:
      - runner

jobs:
  runner:
    machine: true
    resource_class: exo/hardware
    steps:
      # Step 1: Check out the repository
      - checkout

      # Step 3: Install dependencies
      - run:
          name: init venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install aiohttp

      # Step 4: Run the Python script
      - run:
          name: run
          command: |
            . venv/bin/activate
            python3 $HOME/exo/explore/.circleci/benchmark.py
