version: 2.1

workflows:
  build-workflow:
    jobs:
      - runner
jobs:
  runner:
    machine: true
    resource_class: hardware/macos  # {project name}/{identifier}
    steps:
      - run: echo "Hi I'm on Runners!"