version: 2.1

jobs:
  check_chip:
    parameters:
      runner_name:
        type: string
    machine: true
    resource_class: << parameters.runner_name >>
    steps:
      - run:
          name: Debug chip info
          command: |
            echo "Full CPU info:"
            sysctl -n machdep.cpu.brand_string
            
            echo "Extracted chip:"
            CHIP=$(sysctl -n machdep.cpu.brand_string | grep -o "M[1-4]" || echo "Unknown")
            echo $CHIP

workflows:
  check-chips:
    jobs:
      - check_chip:
          matrix:
            parameters:
              runner_name: ["exo/hardware", "exo/hardware"]