version: 2.1

workflows:
  testing:
    jobs:
      - benchmark

jobs:
  benchmark:
    machine: true
    resource_class: exo/hardware-runner-j4r75p27fq
    steps:
      - checkout
      - run:
          name: build exo
          command: |
            /opt/homebrew/bin/python3.12 -m venv venv
            source venv/bin/activate
            pip install -U pip
            pip install -e .
      - run:
          name: run exo
          command: |
            exo
