version: 2.1

parameters:
  target_chip:
    type: string
    default: "M1"
    description: "Target chip to find"

jobs:
  check_chip:
    parameters:
      instance:
        type: string
    machine: true
    resource_class: "exo/hardware"
    steps:
      - run:
          name: Check for chip
          command: |
            echo "Hostname: $(hostname)"
            CHIP=$(sysctl -n machdep.cpu.brand_string | grep -o "M[1-4]" || echo "Unknown")
            echo "Found chip: $CHIP"
            
            if [[ "$CHIP" == "<< pipeline.parameters.target_chip >>" ]]; then
              echo "Match found! Hello $CHIP"
              exit 0
            else
              echo "This machine doesn't have << pipeline.parameters.target_chip >>"
              exit 1
            fi

workflows:
  check-chips:
    jobs:
      - check_chip:
          matrix:
            parameters:
              instance: ["1", "2"]