version: 2.1

workflows:
  benchmark:
    jobs:
      - hardware-runner-e0

jobs:
  runner:
    machine: true
    resource_class: exo/hardware
    steps:
      - checkout
      - run:
        echo "hello world"
      # - run:
      #     name: benchmark
      #     command: |
      #       python3 -m venv venv
      #       . venv/bin/activate
      #       pip install aiohttp
      #       python3 $HOME/Library/com.circleci.runner/workdir/.circleci/bench.py
      # - store_artifacts:
      #     path: artifacts/benchmark.json
      #     destination: benchmark.json
