version: 2.1
#
workflows:
  testing:
    jobs:
      - runner

jobs:
  runner:
    machine: true
    resource_class: exo/hardware
    steps:
      - checkout
      - run:
          name: init
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install aiohttp
      - run:
          name: ping
          command: |
            echo "Working Directory: $(pwd)"
            ls -all $(pwd)
            . venv/bin/activate
            pip install -e .
            exo --prompt "hello"
      # - run:
      #     name: benchmark
      #     command: |
      #       python3 $HOME/Library/Preferences/com.circleci.runner/workdir/.circleci/bench.py
