# version: 2.1

# workflows:
#   benchmark:
#     jobs:
#       - hardware-runner-e0

# jobs:
#   runner:
#     machine: true
#     resource_class: exo/hardware
#     steps:
#       - checkout
#       - run:
#           name: benchmark
#           command: |
#             python3 -m venv venv
#             . venv/bin/activate
#             pip install aiohttp
#             python3 $HOME/Library/com.circleci.runner/workdir/.circleci/bench.py
      # - store_artifacts:
      #     path: artifacts/benchmark.json
      #     destination: benchmark.json


version: 2.1

jobs:
  hello-world:
    machine: true
    resource_class: exo/hardware  # Replace with your actual namespace/resource-class
    steps:
      - checkout
      - run:
          name: Hello from macOS Runner
          command: |
            echo "Hello World from macOS Self-hosted Runner!"
            sw_vers  # Print macOS version information
            echo "Current working directory: $(pwd)"

workflows:
  hello-world-workflow:
    jobs:
      - hello-world
