version: 2.1

jobs:
  hello:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Hello World
          command: echo "Hello, World!"

workflows:
  hello-workflow:
    jobs:
      - hello
